parameters:
  doctrine.connection.name: 'doctrine'
  doctrine.database.name: 'doctrine'
  doctrine.entity.map.file: 'entitymap'
  doctrine.entity.map.extension: '.orm.yml'
  doctrine.dir: 'doctrine'
  doctrine.proxy.name: 'Proxy'

  doctrine.odm.connection.name: 'mongo'
  doctrine.odm.database.name: 'mongo'
  doctrine.odm.dir: 'odm'
  doctrine.odm.map.file: 'entitymap'
  doctrine.odm.map.extension: '.odm.yml'

services:
  doctrine.entity.manager:
    class: Doctrine\ORM\EntityManager
    factory: ['@doctrine.entity.manager.factory', 'create']
    arguments:
      - '@database.mvcc'
      - '@doctrine.config'
      - '@doctrine.event.manager'
      - '@time.factory'
  doctrine.document.manager:
    class: Doctrine\ODM\MongoDB\DocumentManager
    factory: ['@doctrine.document.manager.factory', 'create']
    arguments:
      - '@config'
      - '%doctrine.odm.connection.name%'
      - '@doctrine.odm.config'
      - '@doctrine.event.manager'
      - '@time.factory'
  doctrine.config:
    class: Doctrine\ORM\Configuration
    factory: ['@doctrine.config.factory', getConfiguration]
    arguments:
      - '@doctrine.cache'
      - '%app.env%'
      - '%app.dir%/%config.dir%'
      - '%app.dir%/%cache.dir%/%doctrine.dir%'
      - '%doctrine.proxy.name%'
      - '%doctrine.entity.map.file%'
      - '%doctrine.entity.map.extension%'
  doctrine.config.factory:
    class: Vain\Doctrine\Factory\DoctrineConfigurationFactory
    arguments: ['@api.extension.entity.storage']
  doctrine.odm.config:
    class: Doctrine\ODM\MongoDB\Configuration
    factory: ['@doctrine.odm.config.factory', getConfiguration]
    arguments:
      - '@doctrine.cache'
      - '%app.dir%/%config.dir%'
      - '%app.dir%/%cache.dir%/%doctrine.odm.dir%'
      - '%doctrine.odm.map.file%'
      - '%doctrine.odm.map.extension%'
  doctrine.odm.config.factory:
    class: Vain\Doctrine\Factory\DoctrineODMConfigurationFactory
    arguments: ['@api.extension.entity.storage']
  doctrine.event.manager:
    class: Vain\Doctrine\Event\Manager\DoctrineEventManager
    arguments: ['@time.factory']
  connection.factory.doctrine:
    class: Vain\Doctrine\Connection\Factory\DoctrineConnectionFactory
    arguments: ['@connection.pdo']
  doctrine.connection:
    class: PDOConnection
    factory: ['@connection.factory.doctrine', 'createConnection']
    arguments:
      - '%doctrine.connection.name%'
  database.doctrine:
    class: Vain\Doctrine\Database\DoctrineDatabase
    arguments: ['@config', '@doctrine.config', '@doctrine.connection', '@doctrine.event.manager', '@database.generator.factory']
  doctrine.cache.memory:
    class: Doctrine\Common\Cache\ArrayCache
  doctrine.cache.apcu:
    class: Vain\Doctrine\Cache\Apcu\DoctrineApcuCache
  doctrine.cache.redis:
    class: Vain\Doctrine\Cache\Redis\DoctrineRedisCache
    arguments: ['@cache.redis']
  doctrine.entity.manager.factory:
    class: Vain\Doctrine\Factory\DoctrineEntityManagerFactory
  doctrine.document.manager.factory:
    class: Vain\Doctrine\Factory\DoctrineDocumentManagerFactory
  entity.factory.doctrine:
    class: Vain\Doctrine\Entity\Factory\DoctrineEntityFactory
    arguments: ['@doctrine.entity.manager']
  document.factory.doctrine:
    class: Vain\Doctrine\Document\Factory\DoctrineDocumentFactory
    arguments: ['@doctrine.document.manager']
  entity.operation.factory.doctrine:
    parent: entity.operation.factory.abstract
    class: Vain\Doctrine\Entity\Operation\Factory\DoctrineEntityOperationFactory
    arguments: ['@doctrine.entity.manager', '@event.resolver', '@collection.event.dispatcher']
  document.operation.factory.doctrine:
    parent: document.operation.factory.abstract
    class: Vain\Doctrine\Document\Operation\Factory\DoctrineDocumentOperationFactory
    arguments: ['@doctrine.document.manager', '@event.resolver', '@collection.event.dispatcher']
  operation.collection.factory.doctrine:
    class: Vain\Doctrine\Operation\Collection\Factory\Decorator\DoctrineCollectionFactoryDecorator
    decorates: operation.collection.factory
    decoration_priority: 300
    arguments: ['@operation.collection.factory.doctrine.inner', '@doctrine.entity.manager']
  doctrine.event.handler:
    parent: event.handler.abstract
    class: Vain\Doctrine\Event\DoctrineEventHandler
    arguments: ['@doctrine.entity.manager']
